apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: net-tools
  labels:
    app: net-tools
spec:
  serviceName: "net-tools"
  selector: 
    matchLabels: 
      app: net-tools
  replicas: 1
  template:
    metadata:
      labels:
        app: net-tools
    spec:
      containers:
      - name: net-tools
        image: wbitt/network-multitool